# Original base file
# https://github.com/microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

# Base OS layer
FROM ubuntu:20.04

# Install prerequistes since it is needed to get repo config for SQL server
RUN export DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y gnupg && \
  apt-get install -yq curl apt-transport-https && \
  # Get official Microsoft repository configuration
  curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
  curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list | tee /etc/apt/sources.list.d/mssql-server.list && \
  curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list && \
  apt-get update && \
  # Install SQL Server from apt (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15doc)
  apt-get install -y mssql-server=15.0.4123.1-5 && \
  # Install Full Text Search
  apt-get install -y mssql-server-fts && \
  # Install SQL Server Tools
  ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

# Run SQL Server process
CMD /opt/mssql/bin/sqlservr
